version: "2"
plugins:
  shellcheck:
    enabled: true
  scss-lint:
    enabled: true
    config: "./lint/.scss-lint.yml"
  fixme:
    enabled: true
  editorconfig:
    enabled: true
    channel: beta
  tslint:
    enabled: true
    channel: beta
    config: "./lint/tslint.json"
exclude_patterns:
- "**/node_modules/"
- "coverage/"
- "dist/"
- "**/font_awesome/"
- "**/fonts/**"
- ".config"
