---
version: "2"
plugins:
  shellcheck:
    enabled: true
  scss-lint:
    enabled: true
    config: "./.config/.sass-lint.yml"
  fixme:
    enabled: true
  editorconfig:
    enabled: true
    channel: beta
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
exclude_patterns:
- "**/node_modules/"
- "coverage/"
- "dist/"
- "**/font_awesome/"
- ".config"
